version: '3.7'
services:
  fitzroy-academy-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app:cached
    environment:
      FLASK_ENV: development
      DB_CONNECTION_STRING: postgresql://postgres@postgres:5432
    depends_on:
      - postgres
    networks: ['fitzroy-network']
  postgres:
    image: "postgres:12-alpine"
    restart: always
    # build:
        # context: ./postgresql
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    networks: ['fitzroy-network']
networks:
  fitzroy-network:

volumes:
  dbdata: