# Documentation for all options in this file:
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: fitzroy-academy-app-frontend

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.app_env} # Defined below; basically 'dev', 'stage', or 'prod'
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-f1e19a9e
    subnetIds:
      - subnet-1f006e65
      - subnet-bd85b4d5
      - subnet-e529ffa9
  environment:
    API_GATEWAY_BASE_PATH: ${self:custom.app_env}

layers:
  psycopg2:
    name: psycopg2
    path: layers
    description: python3 layer for psycopg2
    compatibleRuntimes:
      - python3.6

package:
  exclude:
    - test/**
    - node_modules/**
    - layers/**

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
    layers:
      - {Ref: Psycopg2LambdaLayer}
    environment:
      APP_ENV: ${self:custom.app_env}
      DB_CONNECTION_STRING: ${self:custom.db_connection_string.${self:provider.stage}}
      DB_PASSWORD: ${self:custom.db_password.${self:provider.stage}}

custom:
  # pythonRequirements:
    # dockerizePip: true
  wsgi:
    app: app.app
  app_env: ${opt:stage,'dev'}
  db_connection_string:
    local: sqlite:///dev_db.sqlite?check_same_thread=False
    dev: postgresql+psycopg2://psqluser@fitzroy-academy-app-db.cck3lz5l88rt.us-east-2.rds.amazonaws.com:5432/postgres
    # stage:
    # prod:
  db_password:
    local: ${file(./secrets.yml):local_db_password}
    dev: ${file(./secrets.yml):dev_db_password}
    # stage:
    # prod:


#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
# meh. :
# resources:
#   Resources:
#     DevDBEndpoint:
#       Type: AWS::SSM::Parameter
#       Properties: 
#         Description: String
#         Name: /fitzroy-app-backend/dev/db_endpoint
#         Type: String
#         Value: initial
#     DevDBUsername:
#       Type: AWS::SSM::Parameter
#       Properties: 
#         Description: String
#         Name: /fitzroy-app-backend/dev/db_username
#         Type: String
#         Value: initial
#     DevDBPassword:
#       Type: AWS::SecretsManager::Secret
#       Properties: 
#         Description: Dev DB Password
#         GenerateSecretString:
#           PasswordLength: 30
#           ExcludeCharacters: '@/\'
#           IncludeSpace: false
#         Name: fitzroy-app-backend-dev-db_password

plugins:
  - serverless-python-requirements
  - serverless-wsgi
