version: 2.1
workflows:
  build_and_deploy_test:
    jobs:
      - build:
          filters:
            branches:
              only: ci-deployment
jobs:
  build:
    machine: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # - run tests
      - run: docker build -t fitzroyacademy/web-app:$CIRCLE_BRANCH .
      # push docker container to registry
  # run tests on container
  # deploy to AWS
