version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          context: fitzroy-circleci
          requires:
            - test
          filters:
            branches:
              only:
                - /v[0-9]+\.[0-9]+(?:\.[0-9])?/
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python nosetests
          
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            sudo apt-get install libpq-dev
            chmod +x scripts/assume-role.sh
      - run:
          name: Build and tag Docker containers
          command: |
            source scripts/assume-role.sh
            docker build -t fitzroy-academy/web-app .
            image_id=$(docker images fitzroy-academy/web-app -q)
            docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_BRANCH}
            docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_SHA1}

            $(aws ecr get-login --region us-east-2 --no-include-email)

            docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_BRANCH}
            docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_SHA1}

            BRANCH_REGEX="(v[0-9]{1,2}\..*)"
            if [[ $CIRCLE_BRANCH =~ $BRANCH_REGEX ]];
            then
              docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:latest
              docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:latest
            fi

      - run:
          name: Deploy application
          command: |
            BRANCH_REGEX="(v[0-9]{1,2}\..*)"
            if [[ $CIRCLE_BRANCH =~ $BRANCH_REGEX ]];
            then
              source scripts/assume-role.sh
              aws ecs update-service --cluster sandbox-web-app-cluster --service web-app --force-new-deployment --region us-east-2
            fi
