version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: fitzroy-circleci
          filters:
            branches:
              only:
                - master
                - circleci-tests
                - /v[0-9]+\.[0-9]+(?:\.[0-9])?/
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            sudo apt-get install libpq-dev
            pip install -r requirements.txt
            nosetests
      - run:
          name: Build and tag Docker containers
          command: |
            image_id=$(docker images fitzroy-academy/web-app -q)
            docker build -t fitzroy-academy/web-app .
            docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_BRANCH}
            docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_SHA1}
            docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_BRANCH}
            docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:${CIRCLE_SHA1}

            if [ "$CIRCLE_BRANCH" != "master" ]; then
              docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:latest
            fi

      - run:
          name: Deploy application
          command: |
            $(aws ecr get-login --region us-east-2 --no-include-email)
             if [ "$CIRCLE_BRANCH" != "master" ]; then
              docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:latest
              docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fitzroy-academy/web-app:latest
            fi
            if [ ! $CIRCLE_PULL_REQUEST  && "$CIRCLE_BRANCH" != "master" ]; then
              chmod +x scripts/assume-role.sh
              source scripts/assume-role.sh
              aws ecs update-service --cluster sandbox-web-app-cluster --service web-app --force-new-deployment --region us-east-2
            fi