version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: fitzroy-circleci
          filters:
            branches:
              only: ci-deployment
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # - run tests
      - run: docker build -t fitzroyacademy/web-app:latest .
      - run:
          name: Deploy application
          command: |
            chmod +x scripts/assume-role.sh
            source scripts/assume-role.sh
            image_id=$(docker images fitzroyacademy/web-app -q)
            $(aws ecr get-login --region us-east-1 --no-include-email)
            docker tag $image_id $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/web-app
            docker push $SANDBOX_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/web-app

      # push docker container to registry
  # run tests on container
  # deploy to AWS