version: 2.1
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: ci-deployment
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      # - checkout
      # - run tests
      # - run: docker build -t fitzroyacademy/web-app:$CIRCLE_BRANCH .
      - run:
          context: fitzroy-circleci
          name: Deploy application
          command: |
            chmod +x scripts/assume-role.sh
            source scripts/assume-role.sh
      # push docker container to registry
  # run tests on container
  # deploy to AWS
