SURVEYS_TEMPLATES = [
    {
        "survey_id": "plain_text_1",
        "default": True,
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "plain_text",
        "survey_type_name": "Plain text",
        "survey_type_description": "Simple text box for students to type their thoughts.",
        "survey_type_icon": "fal fa-comment-lines",
        "survey_type_icon_type": "css",
        "answer_template": {"survey_id": "plain_text_1", "reason_response": ""},
    },
    {
        "survey_id": "emoji_happiness_1",
        "default": False,
        "survey_template_version": "1.0",
        "question": "How do you feel about the course?",
        "min_response_length": 0,
        "survey_type": "emoji",
        "survey_type_name": "Happiness",
        "survey_type_description": "3 faces, from angry to happy, with labels.",
        "survey_type_icon": "fal fa-smile",
        "survey_type_icon_type": "css",
        "answer_template": {
            "survey_id": "",
            "reason_response": "",
            "chosen_answer": "",
        },
        "choice_questions": [
            {
                "icon": "fal fa-angry",
                "icon_type": "css",
                "single_word": "Terrible",
                "short_sentence": "I feel terrible",
                "id": "",
            },
            {
                "icon": "fal fa-frown",
                "icon_type": "css",
                "single_word": "Bad",
                "short_sentence": "I feel pretty bad",
                "id": "",
            },
            {
                "icon": "fal fa-meh",
                "icon_type": "css",
                "single_word": "Meh",
                "short_sentence": "Meh, not sure",
                "id": "",
            },
            {
                "icon": "fal fa-smile",
                "icon_type": "css",
                "single_word": "Good",
                "short_sentence": "Overall pretty good",
                "id": "",
            },
            {
                "icon": "fal fa-grin",
                "icon_type": "css",
                "single_word": "Great",
                "short_sentence": "Feeling great, thanks!",
                "id": "",
            },
            {
                "icon": "fal fa-grin-stars",
                "icon_type": "css",
                "single_word": "Amazing",
                "short_sentence": "OMG I feel amazing!",
                "id": "",
            },
        ],
    },
    {
        "survey_id": "emoji_thumbs_1",
        "default": False,
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "emoji",
        "survey_type_name": "Thumbs",
        "survey_type_description": "Simple thumbs up / thumbs down selector",
        "survey_type_icon": "fal fa-thumbs-up",
        "survey_type_icon_type": "css",
        "answer_template": {
            "survey_id": "emoji_thumbs_1",
            "reason_response": "",
            "chosen_answer": "",
        },
        "choice_questions": [
            {
                "icon": "fal fa-thumbs-up",
                "icon_type": "css",
                "single_word": "Great",
                "short_sentence": "Feeling great, thanks!",
                "id": "",
            },
            {
                "icon": "fal fa-thumbs-down",
                "icon_type": "css",
                "single_word": "I'm stuck!",
                "short_sentence": "I am stuck and I need some help.",
                "id": "",
            },
        ],
        "free_text_require": False,
        "free_text_entry": "",
    },
    {
        "survey_id": "ten_point_scale_1",
        "default": False,
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "points_scale",
        "survey_type_name": "10 points scale",
        "survey_type_description": "Simple thumbs up / thumbs down selector",
        "survey_type_icon": "fal fa-tachometer-fast",
        "survey_type_icon_type": "css",
        "answer_template": {
            "survey_id": "points_scale_1",
            "reason_response": "",
            "chosen_answer": "",
        },
        "left_label": "Absolutely not",
        "right_label": "Definitely!",
        "scale_start": 1,
        "scale_stop": 10,
        "free_text_require": False,
        "free_text_entry": "",
    },
]
