SURVEYS_TEMPLATES = [
    {
        "survey_id": "plain_text_1",
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "plain_text",
        "survey_type_name": "Plain text",
        "survey_type_description": "Simple text box for students to type their thoughts.",
        "survey_type_icon": "https://some-fancy-url-with-very-fancy-icon",
        "survey_type_icon_type": "url",
        "answer_template": {"survey_id": "plain_text_1", "reason_response": ""},
    },
    {
        "survey_id": "emoji_happiness_1",
        "survey_template_version": "1.0",
        "question": "How do you feel about the course?",
        "min_response_length": 0,
        "survey_type": "emoji",
        "survey_type_name": "Happiness",
        "survey_type_description": "3 faces, from angry to happy, with labels.",
        "survey_type_icon": "https://some-fancy-url-with-very-fancy-icon",
        "survey_type_icon_type": "url",
        "answer_template": {
            "survey_id": "",
            "reason_response": "",
            "chosen_answer": "",
        },
        "choice_questions": [
            {
                "icon": "https://again-again-and-so-on.png",
                "icon_type": "url",
                "single_word": "Terrible",
                "short_sentence": "I feel terrible",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-2.png",
                "icon_type": "url",
                "single_word": "Bad",
                "short_sentence": "I feel pretty bad",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-3.png",
                "icon_type": "url",
                "single_word": "Meh",
                "short_sentence": "Meh, not sure",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-3.png",
                "icon_type": "url",
                "single_word": "Good",
                "short_sentence": "Overall pretty good",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-3.png",
                "icon_type": "url",
                "single_word": "Great",
                "short_sentence": "Feeling great, thanks!",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-3.png",
                "icon_type": "url",
                "single_word": "Amazing",
                "short_sentence": "OMG I feel amazing!",
                "id": "",
            },
        ],
    },
    {
        "survey_id": "emoji_thumbs_1",
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "emoji",
        "survey_type_name": "Thumbs",
        "survey_type_description": "Simple thumbs up / thumbs down selector",
        "survey_type_icon": "https://some-fancy-url-with-very-fancy-icon",
        "survey_type_icon_type": "url",
        "answer_template": {
            "survey_id": "emoji_thumbs_1",
            "reason_response": "",
            "chosen_answer": "",
        },
        "choice_questions": [
            {
                "icon": "https://again-again-and-so-on.png",
                "icon_type": "url",
                "single_word": "Great",
                "short_sentence": "Feeling great, thanks!",
                "id": "",
            },
            {
                "icon": "https://again-again-and-so-on-2.png",
                "icon_type": "url",
                "single_word": "I'm stuck!",
                "short_sentence": "I am stuck and I need some help.",
                "id": "",
            },
        ],
    },
    {
        "survey_id": "ten_point_scale_1",
        "survey_template_version": "1.0",
        "question": "",
        "min_response_length": 0,
        "survey_type": "points_scale",
        "survey_type_name": "Thumbs",
        "survey_type_description": "Simple thumbs up / thumbs down selector",
        "survey_type_icon": "https://some-fancy-url-with-very-fancy-icon",
        "survey_type_icon_type": "url",
        "answer_template": {
            "survey_id": "emoji_thumbs_1",
            "reason_response": "",
            "chosen_answer": "",
        },
        "left_label": "Absolutely not",
        "right_label": "Definitely!",
        "scale_start": 1,
        "scale_stop": 10,
    },
]
